### ISSUE TITLE
settings tab always opens

### ISSUE THREAD

**Issue by slag-dev** [rickbutterfield/Our.Umbraco.BlockPreview#10]
the settings tab always opens when you want to add new content inside a block

![image](https://user-images.githubusercontent.com/56881874/220901672-bf850524-c7a1-45f5-863c-bbaf93f1a47d.png)

**Comment by rickbutterfield** [comment]
Thanks @slag-dev! Fixed, and will be released in v1.1.0

**Comment by slag-dev** [comment]
Hi @rickbutterfield 

thanks for your feedback - I just tried the newest version 1.1.0, unfortunately both windows still open when I want to add a new block item inside a block. 

with existing blocks it seems to work where content is already added. I guess only with new ones it happens like the image above from my first post.

for instance BLOCK "one column" and inside "Add Content" opens first the settings windows and behind the new block overview...

I found the issue. you have to extend this line in the file block-preview.controller.js:

`var actions = target.closest('.umb-block-grid__block--actions')
              || target.closest('.umb-block-grid__area-actions')
              || target.closest('.umb-block-grid__block--inline-create-button')
              || target.closest('.umb-block-grid__block--last-inline-create-button');`

**Comment by rickbutterfield** [comment]
@slag-dev Please can you give v1.1.1 a try? 1.1.0 wasn't copying the updated files in `App_Plugins` so you might not have been getting the latest JS. If that doesn't work, then I'll test the fix you've listed above!

**Comment by slag-dev** [comment]
Hi @rickbutterfield 

it seems to work now :).

Thx
