### ISSUE TITLE
v1.1.2 seems to break all block previews

### ISSUE THREAD

**Issue by patrickdemooij9** [rickbutterfield/Our.Umbraco.BlockPreview#13]
Hi,

I just upgraded from v1.1.0 to v1.1.2, but now it seems like all my blocks are not rendering correctly anymore. I am running Umbraco 11.2.0 and see the following error in my console:
![image](https://user-images.githubusercontent.com/11466511/225114596-8ce6c76e-be21-4328-9975-ec7418eff22f.png)

I did notice that there are now two app plugins folders so I tested with both files, but they both give the same issues
![image](https://user-images.githubusercontent.com/11466511/225114888-f0def99f-a983-4fb5-b0b8-319499899b17.png)

Is there anything else that I have to change to get the version working?

**Comment by patrickdemooij9** [comment]
Hmm, seems like I've been able to figure it out. The update doesn't clean up the Our.Umbraco.BlockPreview folder which will then load in duplicate controllers (I think) which causes issues with Umbraco.

Deleting the Our.Umbraco.BlockPreview folder and setting all my block list items to the new folder seems to fix this.

**Comment by rickbutterfield** [comment]
That is good to know! Are you still using the Our.Umbraco.BlockPreview version of the package? I'll add a cleanup task to both anyway but just curious to know
