### ISSUE TITLE
Variants not updating content

### ISSUE THREAD

**Issue by kows** [rickbutterfield/Our.Umbraco.BlockPreview#16]
When outputting culture specific content (currency format, dictionary values) inside the blocks Razor views,
this does not seem to apply the variant's culture.

**Comment by rickbutterfield** [comment]
I've managed to replicate this issue. The culture isn't being shared to the thread all the way down the call stack, so I'm having to set it again just before the preview is rendered. Will be released in 1.2.0.

**Comment by rickbutterfield** [comment]
Fixed in v1.2.0!
