### ISSUE TITLE
Null exception for invariant content

### ISSUE THREAD

**Issue by dvandevliet** [rickbutterfield/Our.Umbraco.BlockPreview#18]
Hi,

i just created a pull request #17 to fix a null exception that can be thrown by the code when working with invariant content where the language is not set on the variants language property, but we need to use the culture set on the node (or that part of the content tree).

I was not sure if I should have started this by creating an issue first. Anyways,I like your module and hope this change will help more people.

David

**Comment by rickbutterfield** [comment]
@dvandevliet v1.3.0 has just been released on NuGet with your first contribution, a big #h5yr!
