### ISSUE TITLE
Error rendering preview for block "Value cannot be null. (Parameter 'name')"

### ISSUE THREAD

**Issue by claushingebjerg** [rickbutterfield/Our.Umbraco.BlockPreview#20]
After succesfull install and build i get the following error when viewing a page in the backoffice, with a block grid item
![Skærmbillede 2023-05-23 kl  09 53 07](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/1854789/86412cb7-46a0-4c0d-bcfa-4fcceada5d77)

```
Error rendering preview for block 
System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Umbraco.Community.BlockPreview.Services.BackOfficePreviewService.SetCulture(String culture)
   at Umbraco.Community.BlockPreview.Services.BackOfficeGridPreviewService.GetMarkupForBlock(BlockValue blockValue, ControllerContext controllerContext, String culture)
   at Umbraco.Community.BlockPreview.Controllers.BlockPreviewApiController.PreviewMarkup(BlockValue data, Int32 pageId, Boolean isGrid, String culture)
```

I have set the custom view as described
![Skærmbillede 2023-05-23 kl  09 42 13](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/1854789/e48f24d0-a6cd-4c4b-8797-8bff4711e7e8)

I have set a culture as well (as a desperate attempt :))
![Skærmbillede 2023-05-23 kl  09 46 00](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/1854789/e1046636-09de-4225-9735-7489041ddefb)

**Comment by rickbutterfield** [comment]
I believe this may be the same issue raised in #18, I'll be reviewing that PR this week and hopefully making a new 1.3.0 release

**Comment by karltynan** [comment]
This is exactly the same issue I am seeing - can't wait to see 1.3.0 released to fix it 🙂

**Comment by claushingebjerg** [comment]
Me too, it's gonna be awesome :) #H5YR to rickbutterfield for a great package

**Comment by rickbutterfield** [comment]
Thanks for confirming, aiming to release 1.3.0 just before Codegarden!

**Comment by tony-gledhill** [comment]
Hi @rickbutterfield, do you have an estimated release date for 1.3.0 please :)

**Comment by rickbutterfield** [comment]
@tony-gledhill @karltynan @claushingebjerg v1.3.0 has just been released on NuGet! 🎉

**Comment by karltynan** [comment]
Wonderful news - thank you so much for your time and effort on this! 😃  #h5yr
