### ISSUE TITLE
Umbraco 12 version?

### ISSUE THREAD

**Issue by robertjf** [rickbutterfield/Our.Umbraco.BlockPreview#27]
Hi there,

It seems that the latest release has a dependency < 11.0.0 - is it possible to to get this upgraded to support Umbraco 11 and 12?

**Comment by rickbutterfield** [comment]
Hi @robertjf! This is how it appears in my NuGet, is it not the same for you? Shows support for Umbraco 10 on NET6.0 and Umbraco 11 and 12 on NET7.0

![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/200450/ea174491-e7c2-4051-ba9a-9ea2957b8e10)

**Comment by robertjf** [comment]
@rickbutterfield hm.  Using Visual Studio for Mac (Umbraco 12 here) - must be a bug in their implementation:

![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/818101/a6f94590-0512-4d4c-abb0-e5fac395ae8c)

It did indeed install happily, so all good :). Sorry for the false positive!
