### ISSUE TITLE
Angular errors and blocks missing (Umb 10.4.0)

### ISSUE THREAD

**Issue by AaronSadlerUK** [rickbutterfield/Our.Umbraco.BlockPreview#3]
Hey Rick!

I've followed your readme and my blocks have completely dissapeared with a ton of angularjs errors in the console.

This is using the Block List Editor on Umbraco 10.4.0

### Before
![image](https://user-images.githubusercontent.com/9937803/216449142-4fcec599-3fcf-45b8-b9a1-b65f51688913.png)

### After
![image](https://user-images.githubusercontent.com/9937803/216449057-9c6328eb-1205-454b-aafb-945ee31905d8.png)

I also cannot see `block-[grid|list]-preview.html` only `block-preview.html`

![image](https://user-images.githubusercontent.com/9937803/216448984-40baed76-1b97-4f49-a39b-3aeece9e61a1.png)

This is how I have configured the blocks:

![image](https://user-images.githubusercontent.com/9937803/216448927-3c0f3d09-e5e2-432e-b0a0-4451bd31cc71.png)

And this is the error in the console:

![image](https://user-images.githubusercontent.com/9937803/216449165-cdbeec2d-9c0f-4f5c-994d-6862c6621d1f.png)

Any help figuring this out would be amazing!

**Comment by rickbutterfield** [comment]
Thanks for flagging @AaronSadlerUK! I've turned the package into a multi-targeted one for `net6.0` and `net7.0` as the `Startup` wasn't running for NET6/Umbraco 10. Try installing v1.0.1 when you can and see if that works?

Also updated the README to point to the correct Angular file name in the back office.

**Comment by AaronSadlerUK** [comment]
Perfect that works a treat!
