### ISSUE TITLE
Bootstrap alert and block-preview.css

### ISSUE THREAD

**Issue by BillyDigi** [rickbutterfield/Our.Umbraco.BlockPreview#34]
Hi, I noticed that in v1.6.0 some styling was added (https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/commit/4105ea603c7d2543fdafc25febbc515e291ba422#diff-e8d7af189a8df476ef7a1ef4ef7b0fca6ca87ab09224c07ed09e05cb3b75a7f2)

The same .alert classes are used by bootstrap (https://getbootstrap.com/docs/5.3/components/alerts/). 

My previews changed from :

![alerts](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/28921505/773617b5-4103-43b4-8421-1d5cd96111d6)

to 

![alert-2](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/28921505/30b9ff4b-e0d1-4c04-bb20-8cf56bfbc19e)

Could you perhaps update your classes to a more scoped naming?

**Comment by rickbutterfield** [comment]
Thanks for flagging @BillyDigi - this will be fixed in v1.8.1, releasing later today
