### ISSUE TITLE
Does not work when published to linux

### ISSUE THREAD

**Issue by huwred** [rickbutterfield/Our.Umbraco.BlockPreview#38]
The block preview doesn't work if you publish a release version and host it on linux (lots of angular errors in the back office)

If however you publish in debug mode then all works ok. I suspect it may be something to do with smidge.

**Comment by rickbutterfield** [comment]
@huwred I have managed to release both v1.7.1 on Umbraco 12 and (the newly released) v1.8.0 on Umbraco 13 today, both deployed on Linux in App Services without any issues.

Can you provide any screenshots or copy the error text please?

**Comment by huwred** [comment]
I will retry it today and let you know how it goes.

**Comment by huwred** [comment]
cleared out everything and republished with latest Umbraco 12, all now appears to be working, so please close issue :)

**Comment by rickbutterfield** [comment]
Thanks for confirming!
