### ISSUE TITLE
Preview is sending incorrect isgrid

### ISSUE THREAD

**Issue by bielu** [rickbutterfield/Our.Umbraco.BlockPreview#50]
### Which Umbraco.Community.BlockPreview version are you using?

1.8.3

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.2.2

### Bug summary

If you nest block list editor in block grid, it will try render block list as block grid

### Steps to reproduce

create document with grid,
in grid create block which takes block list,
in block list create component which uses grid
LMK if you need any more information on it

### Expected result / actual result

Block list view is loaded as block list

**Comment by rickbutterfield** [comment]
If you could add a test site, some screenshots, or even export your doctypes and list how your data types are set up that would be super helpful! Otherwise I will try and replicate as you're saying.

**Comment by bielu** [comment]
I might find some time over weekend to prepare you example for it, sadly ebcause of bank holiday in Uk I have really busy week 😅

**Comment by rickbutterfield** [comment]
Hey @bielu! I never commented on this, but this was fixed in v1.8.4!
