### ISSUE TITLE
Previews not working after updating to 1.8.3

### ISSUE THREAD

**Issue by OwainJ** [rickbutterfield/Our.Umbraco.BlockPreview#51]
### Which Umbraco.Community.BlockPreview version are you using?

1.8.3

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.2.2

### Bug summary

After updating from 1.8.2 to 1.8.3, the block list previews have stopped working.
![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/17008780/04e4d362-80be-4102-a716-199a2ddd6ed0)

Downgrading back to 1.8.2 fixes the issue, and the previews render as expected.

There are no errors in the browser console, or the Umbraco log, but I can see that the preview markup API response is empty:
![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/17008780/7c025f61-955c-475f-ac77-d9552735c354)

Whereas on 1.8.2, the response looks like this:
![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/17008780/00c168b6-b1f8-4a8c-90f2-4cd8bf110a5e)

### Steps to reproduce

- Update from 1.8.2 to 1.8.3

I haven't tried reproducing this on a fresh install yet, will update when I do.

### Expected result / actual result

Previews should render.

**Comment by bielu** [comment]
@OwainJ I think it might be same issue / or related, as this one:
https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/issues/50
can you try to move them to blockgrid folder just to see if is the same?

**Comment by OwainJ** [comment]
Hi @bielu, yup, can confirm that moving my `/Components` folder from `/blocklist` to `/blockgrid` got the rendering working:

1 |  2
:-------------------------:|:-------------------------:
![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/17008780/d775b15f-4ffa-4e4f-9d14-3656880bc458) | ![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/17008780/ac9363bd-f6e4-4b77-a6ed-0ac8a3a9a75b)

**Note:** my block list is not nested like in #50, it's just a property on a DocType

**Comment by bielu** [comment]
interesting!

**Comment by AlexanderWagner82** [comment]
I have the same problem with Umbraco.Csm 13.3.0 with Umbraco.Community.BlockPreview 1.8.2 and 1.8.3. In this case I'm using a blocklist

**Comment by AlexanderWagner82** [comment]
I'm having the same problem with Umbraco.Cms 13.3.0, Umbraco.Community.BlockPreview both with 1.8.2 and 1.8.3.

Works perfectly with Umbraco.Cms 13.2.2 and BlockPreview 1.8.2

**Comment by rickbutterfield** [comment]
Hi @OwainJ, @AlexanderWagner82

There's a fix for this (of course it one only a one liner!!) that's being released as v1.8.4 right now. Please give it a try once released to NuGet and let me know how you get on.

**Comment by OwainJ** [comment]
Happy to confirm that it works perfectly for me now on v1.8.4! Cheers Rick!

**Comment by AlexanderWagner82** [comment]
Works like a charm on Umbraco.Cms 13.3.0. Thank you very much!
