### ISSUE TITLE
Enhanced preview capability when creating a page using content templates

### ISSUE THREAD

**Issue by giordano-uselab** [rickbutterfield/Our.Umbraco.BlockPreview#52]
### Feature summary

When creating a new page with a content template, it would be convenient to preview blocks without having to save the page initially.

### Additional details

When utilizing a content template with sample content in a block grid to create a new page, you may encounter the alert: "Cannot create a preview: the page must be saved before a preview can be created.". Its purpose is to inform you that although there is sample content within the block grid, it won't be visible on the CMS until you save the page (publishing is not necessary, just saving is sufficient). This is the designed behavior for the BlockPreview component.

It would be advantageous to enable previewing blocks without having to save the page initially.

<img width="743" alt="image" src="https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/159016404/712d2f7f-ea6b-424d-8e2c-326100d3f541">

**Comment by rickbutterfield** [comment]
Hey @giordano-uselab, this is now in v1.10+ of BlockPreview!
