### ISSUE TITLE
Update docs to cover V13 with no startup.cs

### ISSUE THREAD

**Issue by craigs100** [rickbutterfield/Our.Umbraco.BlockPreview#58]
### Feature summary

Currently the installation instructions are for older versions of Umbraco that had a startup.cs.  Modern versions now conform to the Minimal Hosting Requirements protocol and so don't use a startup.cs.  Could you please add instructions as to how to get it working on modern versions? We're not all C# ninjas capable of making the switch unaided ;)

Thanks.

**Comment by rickbutterfield** [comment]
Hey @craigs100! If you're using a version ≥1.7.0, there is nothing you need to add to `Startup.cs` or `Program.cs` to make this package work 🙂

**Comment by craigs100** [comment]
"If you are using a version prior to 1.7.0, you will likely have a reference to AddBlockPreview() in your Startup.cs. This can now be removed!"

Sorry, new glasses!

**Comment by rickbutterfield** [comment]
I'm going to tidy up the README, NuGet stats show that versions prior to 1.7.0 aren't being downloaded any more!
