### ISSUE TITLE
Support for RichTextBlockItem

### ISSUE THREAD

**Issue by robertjf** [rickbutterfield/Our.Umbraco.BlockPreview#59]
### Feature summary

With the support for Content Blocks in the RichText Editor, it would be great to be able to have this supported as well.  For reference, see here:

https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-blocks

**Comment by rickbutterfield** [comment]
This is a great idea @robertjf! I haven't used blocks in RTEs yet but as far as I understand the support should be fairly easy to sort. Let me have a play around and get back to you.

**Comment by rickbutterfield** [comment]
Hey @robertjf! I had a look at this over the weekend at it appears that as long as you're running v13.2+, this *should* just work out of the box! Is there something you've tried that hasn't worked?

**Comment by robertjf** [comment]
yeah, it's not really working.  I set the preview template as per normal but in the Richtext Editor the block simply doesn't render at all.

**Comment by rickbutterfield** [comment]
Hey @robertjf - keep an eye out for v1.9.0 releasing later on today, it has full support for `RichTextBlockItem`!
