### ISSUE TITLE
Missing "Add content button"

### ISSUE THREAD

**Issue by craigs100** [rickbutterfield/Our.Umbraco.BlockPreview#60]
### Which Umbraco.Community.BlockPreview version are you using?

1.8.4

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.4.1

### Bug summary

When adding content to a page, adding a layout produces an outlined box when moused over, but no "Add content" button within it.  It is therefore impossible to create content within a layout.

When it "Sort mode" it is impossible to drag a content item into a layout.

### Steps to reproduce

Create a single column layout block and an RTE block as per Umbraco docs.

Add the BlockGrid containing the new blocks to a page's docType.

Ensure the Grid-specific setup instructions are carried out.

Ensure the BlockGrid CSS is attached to the site's master template.

In the Content tree, open the page with the BlockGrid and add the single column layout. Then attempt to add an RTE block, or anything else inside the single column layout.

Add an RTE block underneath the layout, put the property editor into "Sort mode" and attempt to drag the RTE block into the single column layout.  

### Expected result / actual result

Expected result would be to see an "Add content" button inside the single column layout on mousover, and to be able to add blocks within it and rearrange as normal.

Actual result, no "Add content" button available and impossible to drag blocks into the layout in "Sort mode".

I should point out, just in case there's a typo in the code, that I'm developing on Linux Mint.

**Comment by rade-projects** [comment]
Getting the same issue on Windows

**Comment by rickbutterfield** [comment]
Hi @craigs100 and @rade-projects.

This is unfortunately default behaviour for Umbraco's Block Grid, even without the BlockPreview package installed as you can see from these two screenshots from the [Deep Dive: Block Grid Editor Part 1 blog post](https://umbraco.com/blog/deep-dive-block-grid-editor-part-1/)

![Screenshot 1](https://umbraco.com/media/sdyfwuzs/block-grid-editor-content-placeholders-in-the-backoffice_1918x991px.jpg)
![Screenshot 2](https://umbraco.com/media/25unz1ao/block-grid-editor-content-in-the-backoffice_1917x991px.jpg)

As shown above, the "Add content" buttons only appear when there is no content within a nested Area. The way to add content to an Area that already has content is to hover above or below an existing block which gives you this inline add button:

![Screenshot 3](https://docs.umbraco.com/~gitbook/image?url=https%3A%2F%2F3701346516-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FG1Byxw7XfiZAj8zDMCTD%252Fuploads%252Fgit-blob-644ec9d1b1a7c7ec8c2b638bc603667009967b64%252FBlockGridEditor_AddContentInline.png%3Falt%3Dmedia&width=400&dpr=2&quality=100&sign=af9ddd1a&sv=1)

This _may_ be able to be overridden in v14, but I'll have to do some digging

**Comment by craigs100** [comment]
Think you've misunderstood. Unfortunately I can't screenshot it as the overlays disappear, but if I add a single column layout to a previously empty BlockGrid section, I can't then add anything into it. Nor can I in Sort Mode.  I may be able to do a screen recording though.

**Comment by rickbutterfield** [comment]
@craigs100 are you able to provide a link to the steps you followed to create this setup please?

**Comment by rickbutterfield** [comment]
@craigs100 Let me try and recreate following the same steps and see what happens

**Comment by craigs100** [comment]
I was just setting up again to do you a screen recording, so I re-applied the blockpreview.html to the layout and all of a sudden it's working beautifully. It's picking up the layout background and everything.

As you can see above, I wasn't the only one to see this. (@rade-projects ).  Odd. All I can say is that as I'd decided not to use blockpreview.html for the layout and went on to set a few more things up, coming back to it seems to have kicked it into working.

**Comment by rickbutterfield** [comment]
Wonderful to hear @craigs100! @rade-projects I'd love to hear if you're still seeing the same issue?

**Comment by rade-projects** [comment]
I'll experiment a bit more based on what Craigs100 says, thanks - it wasn't urgent on this end so haven't pursued it too much.
