### ISSUE TITLE
Missing block-preview.html for v2.0.0RC2

### ISSUE THREAD

**Issue by parxal** [rickbutterfield/Our.Umbraco.BlockPreview#61]
### Which Umbraco.Community.BlockPreview version are you using?

v2.0.0RC2

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

14.1.1

### Bug summary

Missing block-preview.html for v2.0.0RC2

### Steps to reproduce

Install nuget

### Expected result / actual result

See block-preview.html

**Comment by rickbutterfield** [comment]
Hi @parxal - now that Umbraco 14 is using Web Components, the `block-preview.html` file doesn't exist. Please follow the [instructions in the v2 README](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/blob/v2/dev/.github/README.md) to get up and running, specifically either one of these configurations:

`Program.cs`:
```diff
+using Umbraco.Community.BlockPreview.Extensions;

builder.CreateUmbracoBuilder()
    .AddBackOffice()
    .AddWebsite()
    .AddDeliveryApi()
    .AddComposers()
+   .AddBlockPreview(options =>
+   {
+       // This will enable the preview for every content type
+       options.BlockGrid.Enabled = true;
+   })
    .Build();
```
or `appsettings.json`:
```json
{
  "BlockPreview": {
    "BlockGrid": {
      "Enabled": true
    }
  }
}
```
