### ISSUE TITLE
Previews missing after updating to 1.10.0

### ISSUE THREAD

**Issue by OwainJ** [rickbutterfield/Our.Umbraco.BlockPreview#64]
### Which Umbraco.Community.BlockPreview version are you using?

1.10.0

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.4.1

### Bug summary

After updating to v1.10.0, the block previews are no longer shown.
![image](https://github.com/user-attachments/assets/f78869ae-2dc9-4447-9bc6-e4a56bee9f37)

There are no errors in the browser's console, or the Umbraco log.

v1.9.1 works as expected:
![image](https://github.com/user-attachments/assets/01f22479-03e9-41b3-a7de-570851ba931d)

The above screenshots are taken from a project that uses the Block List, but I have also observed the issue on a project that uses the Block Grid.

### Steps to reproduce

- Update to v1.10.0
- Observe if the previews are still shown

**Comment by rickbutterfield** [comment]
Thanks for raising so quickly @OwainJ! I've deprecated this version on NuGet as I have managed to replicate, but only when installed from there. Will do some digging and let you know once there's a new version out.

**Comment by rickbutterfield** [comment]
@OwainJ out of curiosity, is the doctype you're looking at primarily made up of compositions?

**Comment by OwainJ** [comment]
@rickbutterfield  Yup, it is, the Block List property is from a composition.
![image](https://github.com/user-attachments/assets/7ad11fbf-c9d9-47f9-898c-0b4a032b2b48)

And it's the same on my other project, where the Block Grid is also from a composition.

**Comment by rickbutterfield** [comment]
@OwainJ Thought so! Please give v1.10.1 a go and let me know how you get on 😁

**Comment by OwainJ** [comment]
Hi @rickbutterfield, unfortunately I'm seeing the same thing in v1.10.1; downgrading to v1.9.1 and they show up again.
No errors in the console or log either.

I'll see if I can recreate this on a vanilla project tomorrow and share a .zip here, although I'm on an Umbraco course in the morning, so would be in the afternoon sometime.

**Comment by katie366** [comment]
I am having the same issue after installing version 1.10.3 in 13.4.1. Did anyone find a solution?
Thank you

**Comment by OwainJ** [comment]
Apologies, I didn't get around to testing the new release and it completely slipped my mind!

I've just done a quick test with a fresh install and I get the same issue:
![image](https://github.com/user-attachments/assets/45d1d92d-c49d-4ecc-80a3-c19e1d18fa10)

Here's a .zip of the test project: [BlockPreview_1-10-3_Test.zip](https://github.com/user-attachments/files/16969895/BlockPreview_1-10-3_Test.zip)
- Umbraco v13.4.1
- BlockPreview v1.10.3
- uSync v13.2.5
- Backoffice email: admin@example.com
- Backoffice password: 1234567890
- Project created using this PSW script: https://psw.codeshare.co.uk/?TemplateName=Umbraco.Templates&TemplateVersion=13.4.1&Packages=uSync%7C13.2.5%2CUmbraco.Community.BlockPreview%7C1.10.3&UserEmail=admin%40example.com&ProjectName=BlockPreviewTest.Web&CreateSolutionFile=true&SolutionName=BlockPreviewTest&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=false&StarterKitPackage=Umbraco.BlockGrid.Example.Website&OnelinerOutput=false&RemoveComments=false

**Comment by rickbutterfield** [comment]
Thanks for the test project @OwainJ! The issue here appears to be that ModelsBuilder isn't enabled. Unfortunately the package doesn't work without this enabled as it tries to strongly type the data coming from the backoffice!

I'll add a note to the README about having ModelsBuilder enabled. Is there a use case for you where you'd want to use this without ModelsBuilder? (or @katie366 - I'd be curious to see if it's the same for you!)

**Comment by OwainJ** [comment]
Ahh what silly mistake lol my bad! I have no use case, I just forgot to enable it on the test project.

I've re-tested with Models Builder enabled, and can confirm that it works with the Block Grid, but weirdly, the Block List previews seem to just repeat the preview of the first block:
![Block List Preview Test](https://github.com/user-attachments/assets/14452c97-8607-4ca1-8e1f-57d86bf9feaf)

Here's an updated test project with models builder enabled: 
[BlockPreviewTest_1-10-3_Test-2.zip](https://github.com/user-attachments/files/16992175/BlockPreviewTest_1-10-3_Test-2.zip)

I also tested on one of my client's projects, where `v1.9.1` works as expected, `v1.10.1` showed no previews, and `v1.10.3` has the weird repeating issue on Block List previews:

<details>
  <summary>v1.9.1 screenshot</summary>
  
![image](https://github.com/user-attachments/assets/bef18eb0-99d2-4f25-8acb-2740147f2a8e)

</details>

<details>
  <summary>v1.10.1 screenshot</summary>

![image](https://github.com/user-attachments/assets/30ef3b92-cf0f-46d3-938e-3a4f7c48e502)

</details>

<details>
  <summary>v1.10.3 screenshot</summary>
  
![image](https://github.com/user-attachments/assets/abe243df-cbaa-4a15-bd0e-68153875eb2b)

</details>

Edit: The blocklist on `v1.10.2` behaves the same as `v1.10.3`

**Comment by katie366** [comment]
I have also enabled Models Builder, and have upgraded to v1.10.3 and have got it working. I don't have the repetition or the preview blocks.

Thank you

**Comment by rickbutterfield** [comment]
@OwainJ v1.10.4 is being released right now, with a fix for this!

**Comment by OwainJ** [comment]
Legend 😄 happy to report that `v1.10.4` is working nicely!

**Comment by AleksandrRogov** [comment]
That note about a ModelsBuilder would be helpful still! 🙂
Had this happen with v3. Enabled the builder and the previews started working.
