### ISSUE TITLE
Umbraco 14.3.1 and BlockPreview 2.0.3 - Unable to convert textdata to json

### ISSUE THREAD

**Issue by rgjobb** [rickbutterfield/Our.Umbraco.BlockPreview#80]
### Which Umbraco.Community.BlockPreview version are you using?

2.0.3

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

14.3.1

### Bug summary

Not sure if it is a bug or something I'm doing wrong, since it's the first time I'm trying this package. I keep getting the error message shown in the screenshot below when using it with the block grid editor.

![chrome_QESnFy9Yw4](https://github.com/user-attachments/assets/e758ebf0-5d6f-428d-acef-7ef91ef6ec1a)

I get that even when testing the example website (Umbraco.Cms.14.x in the v2/dev branch). Only the headline block shows a preview there, the other blocks gets the same error message.

I added the options in Program.cs, containing a path to the css and the block in ContentTypes, and the custom view is picked up:

![image](https://github.com/user-attachments/assets/56878be0-aa99-4344-9cef-4e5c0b2e01a5)

Since there is minimal documentation for setting it up for Umbraco14, I might be missing something...

### Steps to reproduce

1. Clean 14.3.1 Umbraco install with Umbraco.Community.BlockPreview 2.0.3 nuget. 
2. Create a rich text editor element/block with a text property.
3. Add a page documenttype with a block grid editor property containing the text block.
4. Add the GetBlockGridHtmlAsync in the page view, and confirm that the Block grid partials are the same as in the demo website (Umbraco.Cms.14.x).
5. Add a Components folder with the block partial for the text widget (just outputing the text).
6. Add the options in the Program.cs (same as Umbraco.Cms.14.x demo website, adding the textBlock in ContentTypes, I also tested with appsettings).
7. Copying the css file (from the Umbraco.Cms.14.x demo website) to wwwroot/css.
8. Restarting umbraco and adding a the text widget/block to the page, and getting the error message shown above.

### Expected result / actual result

Expect to see a preview of the text.

**Comment by rickbutterfield** [comment]
Thanks for raising @rgjobb! I have found a fix for this and it is currently being released in 2.0.4
